#!/bin/bash

function get_source_name() {
    echo $1 | cut -d'.' -f 1 | rev | cut -d'/' -f 1 | rev
}

# Trim lines and white spaces
function oneline() {
    tr  -s '\n' ' ' < $1
}

function create_sass_variable() {
    source_name=$( get_source_name "$1" )
    icon_source=$( oneline "$1" )
    printf "\$icon-%s-source: \'%s\';\n" "$source_name" "$icon_source"
}

function create_sass_variables_from_icons() {
    for svg_file in $(find $1 -type f -iname "*.svg")
    do
        create_sass_variable $svg_file >> $target_file
    done
}

# Target file where the Sass variables should be created
# TODO: Make this an argument that can be passed to script
target_file=./example/example.scss

# First, clear the existing file
> $target_file

# Print comments
printf "// =============================================================================\n" >> $target_file
printf "// SVG TO SASS VARIABLES\n" >> $target_file
printf "// =============================================================================\n" >> $target_file
printf "// This file is automatically generated from svg-to-sass-variable.sh\n\n" >> $target_file

# Then, for each SVG file create a Sass variable and assign SVG content as value
# TODO: Make this an argument that can be passed to script
create_sass_variables_from_icons "example/"